name: Deploy my APIs

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download_sync:
    runs-on: ubuntu-latest
    name: Download Tyk Sync
    steps:
    - uses: asoorm/tyk-sync-action@v0.3
      with:
        tyk-sync-version: 1.2.1
      env:
        DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
        DASHBOARD_SECRET: ${{ secrets.DASHBOARD_SECRET }}
    - run: |
        ls -al
    - run: tyk-sync -h
    - run: tyk-sync sync --path ./apps --dashboard ${DASHBOARD_URL} --secret ${DASHBOARD_SECRET}
